@startuml mascota
class Mascota{
    - salud: Salud int
    + Comer()
    + dormir()
}
class Alimento
class Salud
class felicidad
class sueño
class tristeza
class hambre
class dormir
class Comer 
class sentimientos
class enojado
class frustado
class juguete
class tienda
class edad 
class ropa 
class color
class vehiculos
class Carro 
class avion 
class tiempo
class  amigo 
class  perro 
class  limpieza
class  sucio 
class vida
class alma
class tipos
class  pajaro
class hamster
class gato
class perico
class caballo
class dueño

dueño-->Mascota
Mascota--->hambre
Mascota---*Salud
hambre*---Comer
Salud-->sueño
sueño-->dormir
Mascota--*sentimientos
sentimientos--->felicidad
sentimientos--->enojado
sentimientos--->tristeza
sentimientos--->frustado
Comer---*Alimento
Mascota--->color
vehiculos o---Mascota
vehiculos ---*Carro
vehiculos ---*avion
Mascota---->tiempo
tiempo --*Salud
salud-->Comer
vida-->tiempo
vida-->alma
tiempo--*edad
limpieza--o salud
sucio--o salud
Mascota-->tipos
tipos--*perro
tipos--*gato 
tipos--*perico
tipos--*caballo
tipos--*hamster
tipos--*pajaro
Mascota-->amigo
Mascota--o ropa
dueño--o tienda
tienda-->ropa

@enduml